// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onColorChange();
void onTimeleftChange();
void onBrightChange();
void onNEOPIXELSChange();

CloudColor color;
float timeleft;
float voltage;
int bright;
bool NEOPIXELS;

void initProperties(){

  ArduinoCloud.addProperty(color, READWRITE, ON_CHANGE, onColorChange);
  ArduinoCloud.addProperty(timeleft, READWRITE, ON_CHANGE, onTimeleftChange);
  ArduinoCloud.addProperty(voltage, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(bright, READWRITE, ON_CHANGE, onBrightChange, 255);
  ArduinoCloud.addProperty(NEOPIXELS, READWRITE, ON_CHANGE, onNEOPIXELSChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
